const C=window.QR_LAUNDRY_CONFIG||{}; const app=document.querySelector('#app'); document.querySelector('#brand').textContent=C.shopName||'QR Laundry';
const configured=()=>C.supabaseUrl&&C.supabasePublishableKey;
const sb=configured()?window.supabase.createClient(C.supabaseUrl,C.supabasePublishableKey):null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const services=['전체세척','얼룩제거','탈취','살균','곰팡이제거','발수코팅','가죽관리'];
const photoHtml=(photos=[],label='사진')=>photos.length?`<p class="muted"><strong>${label}</strong></p><div class="photos">${photos.map(p=>`<a href="${esc(p)}" target="_blank"><img src="${esc(p)}" alt="${label}"></a>`).join('')}</div>`:'';
function setup(){app.innerHTML=`<section class="card"><h1>${esc(C.shopName||'QR Laundry')}</h1><p class="muted">QR로 확인하는 세탁 이력 시스템입니다.</p><p class="notice">먼저 Supabase의 Project URL과 Publishable key를 <code>config.js</code>에 넣어 주세요.</p></section>`}
async function customer(code){return careCustomer(code)}
async function login(){app.innerHTML=`<section class="card"><h1>관리자 로그인</h1><p class="muted">처음이라면 ‘관리자 계정 만들기’를 선택하세요.</p><label>이메일</label><input id="email" type="email"><label>비밀번호</label><input id="password" type="password" minlength="8"><button id="sign-in">로그인</button><button class="secondary" id="sign-up">관리자 계정 만들기</button><p id="message"></p></section>`;const msg=document.querySelector('#message');const act=async(signup)=>{const email=document.querySelector('#email').value,password=document.querySelector('#password').value;const r=signup?await sb.auth.signUp({email,password}):await sb.auth.signInWithPassword({email,password});msg.className=r.error?'error':'success';msg.textContent=r.error?r.error.message:(signup?'계정 생성 요청이 완료됐습니다. 이메일 인증 후 로그인하세요.':'로그인됐습니다.');if(!r.error&&!signup)admin()};document.querySelector('#sign-in').onclick=()=>act(false);document.querySelector('#sign-up').onclick=()=>act(true)}
async function upload(files,code,kind){const out=[];for(const file of files){const path=`${code}/${kind}-${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const {error}=await sb.storage.from('laundry-photos').upload(path,file);if(error)throw error;out.push(sb.storage.from('laundry-photos').getPublicUrl(path).data.publicUrl)}return out}
function form(){return `<section class="card" id="new-item"><h1>신규 물건 등록 <span class="muted">(새 QR 생성)</span></h1><p class="muted">처음 맡기는 물건일 때만 사용하세요. 같은 물건은 위의 ‘물건 검색’에서 찾아 사진과 기록을 추가합니다.</p><div class="grid"><div><label>품목</label><select id="type"><option>유모차</option><option>카시트</option><option>명품 스니커즈</option></select></div><div><label>브랜드</label><input id="item-brand" placeholder="예: Bugaboo"></div></div><label>모델명</label><input id="model"><div class="grid"><div><label>고객 이름 (관리자용)</label><input id="customer"></div><div><label>전화번호 (관리자용)</label><input id="phone"></div></div><label>작업 내용</label><div class="checks">${services.map(x=>`<label><input type="checkbox" value="${x}">${x}</label>`).join('')}</div><label>내부 메모 (관리자 전용)</label><textarea id="notes" placeholder="오염, 파손, 요청사항 등"></textarea><label>케어 사진 (여러 장 선택 가능)</label><input id="before" type="file" accept="image/*" multiple>${careInput('new-grade','케어등급 (공개)')}${careExtraFields()}<button id="save">접수 저장 및 QR 만들기</button><p id="result"></p></section>`}
async function admin(){document.body.classList.remove('public-page');const {data:{session}}=await sb.auth.getSession();if(!session)return login();app.innerHTML=`<section class="card"><h1>관리자 화면</h1><p class="muted">물건 검색 → 사진 / 기록 수정 → 저장. 새 물건일 때만 아래에서 새 QR을 만드세요.</p><button id="logout" class="secondary">로그아웃</button></section><section class="card" id="repeat-item"><h1>물건 검색</h1><p class="notice">관리번호·고객 이름·전화번호로 물건을 찾은 뒤 완료된 케어의 사진과 기록을 남기세요. <strong>새 QR을 만들지 않습니다.</strong></p><label>관리번호 또는 고객 정보</label><input id="find" placeholder="관리번호 · 고객 이름 · 전화번호 뒷자리"><button id="findbtn">물건 찾기</button><button id="scanqr" class="secondary">카메라로 QR 스캔</button><div id="scanner"></div><div id="found"></div></section>${form()}`;document.querySelector('#logout').onclick=async()=>{await sb.auth.signOut();login()};document.querySelector('#save').onclick=saveNew;document.querySelector('#findbtn').onclick=findItem;document.querySelector('#scanqr').onclick=startQrScanner;careSettings()}
async function saveNew(){
 const result=document.querySelector('#result'),button=document.querySelector('#save');button.disabled=true;
 try{
  const extra=careExtraValues();const customer_name=document.querySelector('#customer').value,customer_phone=document.querySelector('#phone').value;
  careValidatePublic({customer_name,customer_phone},extra);
  const code='QL-'+crypto.randomUUID().replaceAll('-','').slice(0,8).toUpperCase();
  const photos=await upload(document.querySelector('#before').files,code,'care');
  const item={public_code:code,item_type:document.querySelector('#type').value,brand:document.querySelector('#item-brand').value,model_name:document.querySelector('#model').value,customer_name,customer_phone,care_grade:document.querySelector('#new-grade').value,notes:document.querySelector('#notes').value};
  const selected=[...document.querySelectorAll('#new-item .checks input:checked')].map(x=>x.value);
  const record={...extra,services:extra.processes.length?extra.processes.map(p=>p.name):selected,photos,received_on:careDate(),completed_on:careDate(),status:'완료'};
  const saved=await sb.rpc('create_care_item',{item_data:item,record_data:record});if(saved.error)throw saved.error;
  result.className='success';result.innerHTML='저장됐습니다. 관리번호: <strong>'+esc(code)+'</strong><div class="qr-wrap" id="qr"></div><a class="button" href="/q/'+shortCode(code)+'" target="_blank">고객 화면 열기</a>'+labelButton(code);
  new QRCode(document.querySelector('#qr'),{text:qrUrl(code),width:180,height:180,correctLevel:QRCode.CorrectLevel.M});bindLabelButtons(result);
 }catch(e){result.className='error';result.textContent=e.message;}finally{button.disabled=false;}
}
function qrUrl(code){return `${location.origin}/q/${shortCode(code)}`}
function showQrLabel(code){const url=qrUrl(code);document.querySelector('#qr-label')?.remove();const panel=document.createElement('section');panel.id='qr-label';panel.className='card qr-label';panel.innerHTML=`<h2>QR 라벨</h2><p><strong>관리번호</strong> ${esc(code)}</p><div class="qr-wrap" id="label-qr"></div><label>NIIMBOT에 넣을 주소</label><input id="label-url" readonly value="${esc(url)}"><button id="copy-label-url">주소 복사</button><button id="print-label" class="secondary">일반 프린터로 인쇄</button><button id="close-label" class="secondary">닫기</button><p id="label-message" class="muted"></p>`;app.prepend(panel);new QRCode(document.querySelector('#label-qr'),{text:url,width:220,height:220,correctLevel:QRCode.CorrectLevel.M});document.querySelector('#copy-label-url').onclick=async()=>{const message=document.querySelector('#label-message');try{await navigator.clipboard.writeText(url);message.className='success';message.textContent='주소를 복사했습니다. NIIMBOT 앱의 QR 내용에 붙여 넣으세요.'}catch{document.querySelector('#label-url').select();message.className='muted';message.textContent='주소가 선택되었습니다. 복사해서 NIIMBOT 앱에 붙여 넣으세요.'}};document.querySelector('#print-label').onclick=()=>window.print();document.querySelector('#close-label').onclick=()=>panel.remove()}
function labelButton(code,text='QR 라벨 보기 / 주소 복사'){return `<button class="show-label" data-code="${esc(code)}">${text}</button>`}
function bindLabelButtons(scope=document){scope.querySelectorAll('.show-label').forEach(button=>button.onclick=()=>showQrLabel(button.dataset.code))}
function renderExistingItem(item,out){return careExisting(item,out)}
let activeQrScanner=null;
function scannedCode(value){try{const url=new URL(value,location.origin);const match=url.pathname.match(/^\/q\/([^/]+)\/?$/);return publicCodeFromRoute(match?match[1]:url.searchParams.get('code'))}catch{return publicCodeFromRoute(value)}}
async function startQrScanner(){const holder=document.querySelector('#scanner');if(!window.Html5Qrcode){holder.innerHTML='<p class="error">QR 스캐너를 불러오지 못했습니다. 관리번호나 고객 정보로 검색해 주세요.</p>';return}if(activeQrScanner){try{await activeQrScanner.stop()}catch{}activeQrScanner=null}holder.innerHTML='<p class="muted">카메라에 기존 QR 라벨을 비춰 주세요.</p><div id="qr-reader"></div><button id="stop-scan" class="secondary">스캔 닫기</button><p id="scanmsg"></p>';const msg=document.querySelector('#scanmsg');const scanner=new Html5Qrcode('qr-reader');activeQrScanner=scanner;const stop=async()=>{if(!activeQrScanner)return;try{await activeQrScanner.stop()}catch{}activeQrScanner=null;holder.innerHTML=''};document.querySelector('#stop-scan').onclick=stop;try{await scanner.start({facingMode:'environment'},{fps:10,qrbox:{width:220,height:220}},async text=>{const code=scannedCode(text);if(!code){msg.className='error';msg.textContent='QR에서 관리번호를 찾지 못했습니다.';return}await stop();document.querySelector('#find').value=code;findItem()})}catch(error){activeQrScanner=null;holder.innerHTML='<p class="error">카메라를 시작하지 못했습니다. 카메라 권한을 허용하거나 관리번호·고객 정보로 검색해 주세요.</p>'}}
async function findItem(){const term=document.querySelector('#find').value.trim();const out=document.querySelector('#found');if(!term){out.innerHTML='<p class="error">관리번호, 고객 이름 또는 전화번호를 입력해 주세요.</p>';return}const code=publicCodeFromRoute(term);const isCode=/^QL-[0-9A-F]{8}$/i.test(code);const searchTerm=term.replace(/[(),]/g,'');const request=sb.from('items').select('*,service_records(*)');const {data,error}=isCode?await request.eq('public_code',code):await request.or(`customer_name.ilike.%${searchTerm}%,customer_phone.ilike.%${searchTerm}%`);if(error){out.innerHTML=`<p class="error">조회하지 못했습니다: ${esc(error.message)}</p>`;return}if(!data?.length){out.innerHTML='<p class="error">일치하는 물건을 찾지 못했습니다.</p>';return}if(data.length===1){renderExistingItem(data[0],out);return}out.innerHTML=`<p class="muted"><strong>${data.length}건</strong>을 찾았습니다. 이력을 추가할 물건을 선택하세요.</p><div class="search-results">${data.map((item,i)=>`<article class="record"><strong>${esc(item.public_code)}</strong><p>${esc(item.item_type)} · ${esc(item.brand||'')}</p><p class="muted">관리자용: ${esc(item.customer_name||'이름 미입력')} · ${esc(item.customer_phone||'전화번호 미입력')}</p><button data-item-index="${i}" class="select-item">이 물건 선택</button>${labelButton(item.public_code)}</article>`).join('')}</div>`;document.querySelectorAll('.select-item').forEach(button=>button.onclick=()=>renderExistingItem(data[Number(button.dataset.itemIndex)],out));bindLabelButtons(out)}
function completeForm(item){return careEditor(item)}
function shortCode(publicCode){return String(publicCode||'').replace(/^QL-/i,'').toUpperCase()}
function publicCodeFromRoute(value){const clean=decodeURIComponent(String(value||'')).trim().toUpperCase();return /^[0-9A-F]{8}$/.test(clean)?`QL-${clean}`:clean}
function route(){if(!configured())return setup();const params=new URLSearchParams(location.search);const match=location.pathname.match(/^\/q\/([^/]+)\/?$/);const code=publicCodeFromRoute(match?match[1]:params.get('code'));return location.hash==='#admin'?admin():customer(code)}route();window.addEventListener('hashchange',route);
