const C=window.QR_LAUNDRY_CONFIG||{}; const app=document.querySelector('#app'); document.querySelector('#brand').textContent=C.shopName||'QR Laundry';
const configured=()=>C.supabaseUrl&&C.supabasePublishableKey;
const sb=configured()?window.supabase.createClient(C.supabaseUrl,C.supabasePublishableKey):null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const services=['전체세척','얼룩제거','탈취','살균','곰팡이제거','발수코팅','가죽관리'];
const photoHtml=(photos=[],label='사진')=>photos.length?`<p class="muted"><strong>${label}</strong></p><div class="photos">${photos.map(p=>`<a href="${esc(p)}" target="_blank"><img src="${esc(p)}" alt="${label}"></a>`).join('')}</div>`:'';
function setup(){app.innerHTML=`<section class="card"><h1>${esc(C.shopName||'QR Laundry')}</h1><p class="muted">QR로 확인하는 세탁 이력 시스템입니다.</p><p class="notice">먼저 Supabase의 Project URL과 Publishable key를 <code>config.js</code>에 넣어 주세요.</p></section>`}
async function customer(code){if(!configured())return setup(); if(!code){app.innerHTML=`<section class="card"><h1>세탁 이력 조회</h1><p class="muted">QR 코드를 스캔하면 이력이 표시됩니다.</p></section>`;return} const {data,error}=await sb.rpc('get_qr_history',{lookup_code:code});if(error){app.innerHTML=`<section class="card"><p class="error">조회 중 오류가 발생했습니다.</p></section>`;return}if(!data?.length){app.innerHTML=`<section class="card"><h1>등록된 이력이 없습니다</h1><p class="muted">QR 코드가 맞는지 확인해 주세요.</p></section>`;return}const first=data[0];app.innerHTML=`<section class="card"><h1>${esc(C.shopName||'QR Laundry')} 세탁이력</h1><p class="muted">${esc(first.item_type)} · ${esc(first.brand||'브랜드 미입력')} ${esc(first.model_name||'')}</p><p><strong>관리번호</strong> ${esc(first.public_code)}</p><p class="muted">고객의 이름과 전화번호는 보호를 위해 표시하지 않습니다.</p></section><section class="card"><h2>세탁 진행 이력</h2>${data.map(r=>`<article class="record"><strong>${esc(r.completed_on||r.received_on)}</strong> <span class="tag">${esc(r.status)}</span><div>${(r.services||[]).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div>${r.notes?`<p class="muted"><strong>특이사항</strong> ${esc(r.notes)}</p>`:''}${photoHtml(r.before_photos,'작업 전 사진')}${photoHtml(r.after_photos,'작업 후 사진')}</article>`).join('')}</section>`}
async function login(){app.innerHTML=`<section class="card"><h1>관리자 로그인</h1><p class="muted">처음이라면 ‘관리자 계정 만들기’를 선택하세요.</p><label>이메일</label><input id="email" type="email"><label>비밀번호</label><input id="password" type="password" minlength="8"><button id="sign-in">로그인</button><button class="secondary" id="sign-up">관리자 계정 만들기</button><p id="message"></p></section>`;const msg=document.querySelector('#message');const act=async(signup)=>{const email=document.querySelector('#email').value,password=document.querySelector('#password').value;const r=signup?await sb.auth.signUp({email,password}):await sb.auth.signInWithPassword({email,password});msg.className=r.error?'error':'success';msg.textContent=r.error?r.error.message:(signup?'계정 생성 요청이 완료됐습니다. 이메일 인증 후 로그인하세요.':'로그인됐습니다.');if(!r.error&&!signup)admin()};document.querySelector('#sign-in').onclick=()=>act(false);document.querySelector('#sign-up').onclick=()=>act(true)}
async function upload(files,code,kind){const out=[];for(const file of files){const path=`${code}/${kind}-${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const {error}=await sb.storage.from('laundry-photos').upload(path,file);if(error)throw error;out.push(sb.storage.from('laundry-photos').getPublicUrl(path).data.publicUrl)}return out}
function form(){return `<section class="card"><h1>신규 접수</h1><div class="grid"><div><label>품목</label><select id="type"><option>유모차</option><option>카시트</option><option>명품 스니커즈</option></select></div><div><label>브랜드</label><input id="brand" placeholder="예: Bugaboo"></div></div><label>모델명</label><input id="model"><div class="grid"><div><label>고객 이름 (관리자용)</label><input id="customer"></div><div><label>전화번호 (관리자용)</label><input id="phone"></div></div><label>작업 내용</label><div class="checks">${services.map(x=>`<label><input type="checkbox" value="${x}">${x}</label>`).join('')}</div><label>특이사항</label><textarea id="notes" placeholder="오염, 파손, 요청사항 등"></textarea><label>작업 전 사진</label><input id="before" type="file" accept="image/*" multiple><button id="save">접수 저장 및 QR 만들기</button><p id="result"></p></section>`}
async function admin(){const {data:{session}}=await sb.auth.getSession();if(!session)return login();app.innerHTML=`<section class="card"><h1>관리자 화면</h1><p class="muted">접수 후 QR을 태그에 붙이고, 작업 완료 때 사진과 내용을 추가하세요.</p><button id="logout" class="secondary">로그아웃</button></section>${form()}<section class="card"><h2>기존 물건 찾기</h2><input id="find" placeholder="관리번호를 입력"><button id="findbtn">조회</button><div id="found"></div></section>`;document.querySelector('#logout').onclick=async()=>{await sb.auth.signOut();login()};document.querySelector('#save').onclick=saveNew;document.querySelector('#findbtn').onclick=findItem}
async function saveNew(){const result=document.querySelector('#result');try{const code=`QL-${crypto.randomUUID().replaceAll('-','').slice(0,8).toUpperCase()}`;const before=await upload(document.querySelector('#before').files,code,'before');const item={public_code:code,item_type:document.querySelector('#type').value,brand:document.querySelector('#brand').value,model_name:document.querySelector('#model').value,customer_name:document.querySelector('#customer').value,customer_phone:document.querySelector('#phone').value,notes:document.querySelector('#notes').value};const {data,error}=await sb.from('items').insert(item).select().single();if(error)throw error;const selected=[...document.querySelectorAll('.checks input:checked')].map(x=>x.value);const r=await sb.from('service_records').insert({item_id:data.id,services:selected,notes:item.notes,before_photos:before});if(r.error)throw r.error;result.className='success';result.innerHTML=`저장됐습니다. 관리번호: <strong>${code}</strong><div class="qr-wrap" id="qr"></div><a class="button" href="?code=${code}" target="_blank">고객 화면 열기</a>`;new QRCode(document.querySelector('#qr'),{text:`${location.origin}/q/${shortCode(code)}`,width:180,height:180})}catch(e){result.className='error';result.textContent=e.message}}
async function findItem(){const code=document.querySelector('#find').value.trim();const out=document.querySelector('#found');const {data,error}=await sb.from('items').select('*,service_records(*)').eq('public_code',code).single();if(error){out.innerHTML='<p class="error">찾지 못했습니다.</p>';return}out.innerHTML=`<article class="record"><strong>${esc(data.public_code)}</strong><p>${esc(data.item_type)} · ${esc(data.brand||'')}</p>${data.service_records.map(r=>`<p>${esc(r.received_on)} · ${esc(r.status)} · ${(r.services||[]).map(esc).join(', ')}</p>`).join('')}<button id="complete">새 이력 추가/완료 처리</button></article>`;document.querySelector('#complete').onclick=()=>completeForm(data)}
function completeForm(item){document.querySelector('#found').innerHTML=`<section class="card"><h2>${esc(item.public_code)} 작업 완료</h2><label>완료일</label><input id="done-date" type="date" value="${new Date().toISOString().slice(0,10)}"><label>이번 작업</label><div class="checks">${services.map(x=>`<label><input type="checkbox" value="${x}">${x}</label>`).join('')}</div><label>작업 후 사진</label><input id="after" type="file" accept="image/*" multiple><label>메모</label><textarea id="done-notes"></textarea><button id="finish">완료 이력 저장</button><p id="finishmsg"></p></section>`;document.querySelector('#finish').onclick=async()=>{const msg=document.querySelector('#finishmsg');try{const after=await upload(document.querySelector('#after').files,item.public_code,'after');const selected=[...document.querySelectorAll('#found .checks input:checked')].map(x=>x.value);const {error}=await sb.from('service_records').insert({item_id:item.id,received_on:document.querySelector('#done-date').value,completed_on:document.querySelector('#done-date').value,status:'완료',services:selected,notes:document.querySelector('#done-notes').value,after_photos:after});if(error)throw error;msg.className='success';msg.textContent='완료 이력이 저장됐습니다.'}catch(e){msg.className='error';msg.textContent=e.message}}}
function shortCode(publicCode){return String(publicCode||'').replace(/^QL-/i,'').toUpperCase()}
function publicCodeFromRoute(value){const clean=decodeURIComponent(String(value||'')).trim().toUpperCase();return /^[0-9A-F]{8}$/.test(clean)?`QL-${clean}`:clean}
function route(){if(!configured())return setup();const params=new URLSearchParams(location.search);const match=location.pathname.match(/^\/q\/([^/]+)\/?$/);const code=publicCodeFromRoute(match?match[1]:params.get('code'));return location.hash==='#admin'?admin():customer(code)}route();window.addEventListener('hashchange',route);
