const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
function context(){const app={innerHTML:''};const ctx=vm.createContext({URL,Date,app,C:{},services:['드라이클리닝','얼룩제거'],esc:s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),document:{querySelectorAll:()=>[]}});vm.runInContext(fs.readFileSync(__dirname+'/care.js','utf8'),ctx);return {ctx,app};}
test('public page shows brand, dated care list, escapes content and omits private fields',()=>{const {ctx,app}=context();ctx.payload={item:{public_code:'QL-1234ABCD',item_type:'명품 패딩',brand:'<img onerror=alert(1)>',customer_name:'PRIVATE_NAME',customer_phone:'010-1234-5678'},records:[{received_on:'2026-09-05',notes:'PRIVATE_MEMO',services:['드라이클리닝','얼룩제거'],photos:['https://a.test/1']},{received_on:'2026-03-02',services:['드라이클리닝']}],settings:{kakao_url:'javascript:alert(1)'}};vm.runInContext('renderCarePage(payload)',ctx);const h=app.innerHTML;assert(!h.includes('PRIVATE_'));assert(!h.includes('010-1234'));assert(!h.includes('<img onerror'));assert(h.includes('<dd>2<small>회'));assert(h.includes('2026.09.05'));assert(h.includes('드라이클리닝 · 얼룩제거'));assert(!h.includes('progress-steps'));assert(!h.includes('케어등급'));assert(h.includes('예약 채널 준비 중'));});
test('photo list merges legacy before/after and keeps only https',()=>{const {ctx}=context();ctx.rec={before_photos:['https://a.test/1','javascript:alert(1)'],after_photos:['https://a.test/2']};assert.deepEqual([...vm.runInContext('carePhotoList(rec)',ctx)],['https://a.test/1','https://a.test/2']);ctx.rec2={photos:['https://a.test/9'],before_photos:['https://a.test/1']};assert.deepEqual([...vm.runInContext('carePhotoList(rec2)',ctx)],['https://a.test/9']);});
test('services fall back from legacy processes',()=>{const {ctx}=context();ctx.r={processes:[{name:'스팀 살균'}],services:['x']};assert.deepEqual([...vm.runInContext('careServices(r)',ctx)],['스팀 살균']);ctx.r2={services:['물세탁']};assert.deepEqual([...vm.runInContext('careServices(r2)',ctx)],['물세탁']);});
test('photo picker marks existing photos as kept and drops unsafe URLs',()=>{const {ctx}=context();const html=vm.runInContext("carePhotoPicker(['https://a.test/1','javascript:alert(1)'])",ctx);assert.equal((html.match(/keep-photo/g)||[]).length,1);assert(html.includes('checked'));assert(!html.includes('javascript:'));});
test('service checkboxes preselect existing values',()=>{const {ctx}=context();const html=vm.runInContext("careChecks(['얼룩제거'])",ctx);assert.equal((html.match(/checked/g)||[]).length,1);assert(html.includes('드라이클리닝'));});
test('greeting and per-care comment render, privacy note removed',()=>{const {ctx,app}=context();ctx.payload={item:{public_code:'QL-1234ABCD',item_type:'카시트',brand:'브라이텍스'},records:[{received_on:'2026-09-10',services:['전체세척'],staff_comment:'안감 얼룩은 깨끗이 제거됐습니다.'}],settings:{warranty_text:'소중한 물건을 맡겨주셔서 감사합니다.',business_name:'세탁플랜'}};vm.runInContext('renderCarePage(payload)',ctx);const h=app.innerHTML;assert(h.includes('class="greeting"'));assert(h.includes('소중한 물건을'));assert(h.includes('class="care-comment"'));assert(h.includes('안감 얼룩'));assert(!h.includes('공개하지 않습니다'));});
test('customer comment cannot contain name or phone',()=>{const {ctx}=context();assert.throws(()=>vm.runInContext("careValidateComment({customer_name:'홍길동',customer_phone:'01012345678'},'홍길동님 감사합니다')",ctx));assert.throws(()=>vm.runInContext("careValidateComment({},'연락 010-1234-5678')",ctx));vm.runInContext("careValidateComment({customer_name:'홍길동'},'얼룩 제거 완료')",ctx);});
